# Generated by Django 4.2.3 on 2023-07-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='goal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='really',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='theoric',
            field=models.FloatField(default=0, null=True),
        ),
    ]
